package com.example.guardia.database

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.ColumnInfo

/*
 * SavingsGoal Entity
 This class represents the 'savings_goals' table in the Room database.
 It is used to store financial targets that users wish to reach, allowing
 the app to track progress by comparing current savings to a target amount.
 */
@Entity(tableName = "savings_goals")
data class SavingsGoal(
    /*
     Unique identifier for the savings goal.
     Automatically generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,


    //Foreign key linking the goal to a specific user.

    @ColumnInfo(name = "user_id")
    val userId: Long,


     //The name or title of the goal (e.g., "New Car", "Emergency Fund").
    @ColumnInfo(name = "name")
    val name: String,


     //The total amount of money the user aims to save.

    @ColumnInfo(name = "target_amount")
    val targetAmount: Double,


     //The amount of money the user has currently saved towards this goal.

    @ColumnInfo(name = "current_amount")
    val currentAmount: Double,


    //Timestamp indicating when the goal was created.
    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis()
)
