package com.example.guardia.database

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.ColumnInfo

/*
 User Entity
 This class represents the 'users' table in the Room database.
 Each instance of this class corresponds to a row in the table, storing
 profile information and authentication credentials for a user.
 */
@Entity(tableName = "users")
data class User(
    /*
     Unique identifier for the user.
     Automatically generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,


     //The unique username chosen by the user for identification.
    @ColumnInfo(name = "username")
    val username: String,


     //The user's email address, used for account management.

    @ColumnInfo(name = "email")
    val email: String,


    //The user's hashed or plain-text password (security measures depend on implementation).

    @ColumnInfo(name = "password")
    val password: String,

    /*
     Timestamp indicating when the account was created.
     Defaults to the current system time in milliseconds.
     */
    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis()
)
